### ISSUE TITLE
Rejected stakes stay at the top of the recent transactions list

### ISSUE THREAD

**Issue by DidiMidi** [reddink/reddcoin#4]
Description: Rejected stakes stay at the top of the recent transactions list
Testnet: True
Severity: Minor
Client: v2.0.0rc1c-beta (32 and 64 bit)
OS: Currently replicated on **all OS's** (XP, W7 x32/64, W8.1, W10, MacOS X & Ubuntu)
Replicable: YES
Example screenshot(s): 
http://i.imgur.com/8svwhgV.png 
http://i.imgur.com/Cl5ZW6H.png

**Comment by reddink** [comment]
GUI has been updated to show the Last Transaction in Date order descending.
Bonus, I also increased the number of items to 5.
